export enum DueDiligenceChecklistType {
  ONBOARDING = 'ONBOARDING',
  DEAL_PROCESSING = 'DEAL_PROCESSING',
}

export enum ChecklistItemStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  SATISFACTORY = 'SATISFACTORY',
  ADVERSE = 'ADVERSE',
}