
export enum RegistrationDocumentStatus {
  AWAITING_VIRUS_SCAN="AWAITING_VIRUS_SCAN",
  READY_FOR_REVIEW="READY_FOR_REVIEW"
}

export enum RegistrationStatus {
  READY_FOR_ONBOARDING="READY_FOR_ONBOARDING",
  ONBOARDING_IN_PROGRESS="ONBOARDING_IN_PROGRESS",
  REJECTED="REJECTED",
  APPROVED="APPROVED",
}