export enum AuditEventType {
  LOGIN = 'LOGIN',
  DOCUMENT_CREATED = 'DOCUMENT_CREATED',
  DOCUMENT_UPDATED = 'DOCUMENT_UPDATED',
  DOCUMENT_FILE_UPDATED = 'DOCUMENT_FILE_UPDATED',
  DOCUMENT_STATE_UPDATED='DOCUMENT_STATE_UPDATED',
  DOCUMENT_DELETED = 'DocumentDeleted',
  DOCUMENT_ISSUED = 'DOCUMENT_ISSUED',
  DOCUMENT_DATA_EXTRACTION = 'DOCUMENT_DATA_EXTRACTION',
  DOCUMENT_SIGNED_BY_PARTY = 'DOCUMENT_SIGNED_BY_PARTY',
  DOCUMENT_REVOKED = 'DOCUMENT_REVOKED',
  DOCUMENT_SENT_FOR_FINANCING = 'DOCUMENT_SENT_FOR_FINANCING',
  DOCUMENT_SCHEDULED_FOR_ISSUE = 'DOCUMENT_SCHEDULED_FOR_ISSUE',
  PROCESSING_ERROR='PROCESSING_ERROR',
  DOCUMENT_WRAPPED='DOCUMENT_WRAPPED',
  DOCUMENT_FILE_REPLACED="DOCUMENT_FILE_REPLACED",
  TRACKABLE_DOCUMENT_ISSUED = "TRACKABLE_DOCUMENT_ISSUED",
  DOCUMENT_SIGNING_EVENT_CREATED = "DOCUMENT_SIGNING_EVENT_CREATED",
  DOCUMENT_SIGNED_ON_BEHALF = "DOCUMENT_SIGNED_ON_BEHALF",
  ON_CHAIN_SIGNING_EVENT_CREATED = "ON_CHAIN_SIGNING_EVENT_CREATED",
  ON_CHAIN_SIGNING_EVENT_OPENED = "ON_CHAIN_SIGNING_EVENT_OPENED",

}

