export enum AuditSubject {
  TRADE_DOCUMENT="TRADE_DOCUMENT",
  TRADE_FINANCE_DEAL="TRADE_FINANCE_DEAL",
  AUTHENTICATION="AUTHENTICATION",
  ACCOUNT_USER="ACCOUNT_USER",
  NAMED_WALLET="NAMED_WALLET",
  ACCOUNT_SETTINGS="ACCOUNT_SETTINGS",
  ONBOARDING="ONBOARDING",
  USER_MANAGEMENT="USER_MANAGEMENT",
}

export enum AuditEventType {
  STATUS_CHANGED="STATUS_CHANGED",
  CREATED="CREATED",
  DELETED="DELETED",
  UPDATED="UPDATED",
  PROCESSING_ERROR="PROCESSING_ERROR",

  LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
  LOGIN_FAILED = "LOGIN_FAILED",

  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET = "PASSWORD_RESET",

  // MFA Events
  MFA_SETUP_INITIATED = "MFA_SETUP_INITIATED",
  MFA_SETUP_COMPLETED = "MFA_SETUP_COMPLETED",
  MFA_VERIFICATION_SUCCESSFUL = "MFA_VERIFICATION_SUCCESSFUL",
  MFA_VERIFICATION_FAILED = "MFA_VERIFICATION_FAILED",
  MFA_DISABLED = "MFA_DISABLED",
  MFA_BACKUP_CODES_REGENERATED = "MFA_BACKUP_CODES_REGENERATED",

  // User Management Events
  USER_CREATED = "USER_CREATED",
  USER_INVITED = "USER_INVITED",
  USER_STATUS_CHANGED = "USER_STATUS_CHANGED",

  DOCUMENT_ISSUED="DOCUMENT_ISSUED",
  DOCUMENT_DATA_EXTRACTION="DOCUMENT_DATA_EXTRACTION",
  DOCUMENT_REVOKED = 'DOCUMENT_REVOKED',
  DOCUMENT_WRAPPED='DOCUMENT_WRAPPED',
  DOCUMENT_FILE_ADDED="DOCUMENT_FILE_ADDED",
  DOCUMENT_FILE_REPLACED="DOCUMENT_FILE_REPLACED",
  DOCUMENT_FILE_DELETED="DOCUMENT_FILE_DELETED",
  TRACKABLE_DOCUMENT_ISSUED = "TRACKABLE_DOCUMENT_ISSUED",

  DOCUMENT_SIGNING_EVENT_CREATED = "DOCUMENT_SIGNING_EVENT_CREATED",
  DOCUMENT_SIGNED_ON_BEHALF = "DOCUMENT_SIGNED_ON_BEHALF",
  DOCUMENT_SIGNED_BY_PARTY = 'DOCUMENT_SIGNED_BY_PARTY',
  ON_CHAIN_SIGNING_EVENT_CREATED = "ON_CHAIN_SIGNING_EVENT_CREATED",
  ON_CHAIN_SIGNING_EVENT_OPENED = "ON_CHAIN_SIGNING_EVENT_OPENED",
  DOCUMENT_SIGNING_EXPIRED = "DOCUMENT_SIGNING_EXPIRED",
  DOCUMENT_SIGNING_REVOKED = "DOCUMENT_SIGNING_REVOKED",
  DOCUMENT_SIGNING_COMPLETED = "DOCUMENT_SIGNING_COMPLETED",

  FUNDING_REQUESTED="FUNDING_REQUESTED",
  FUNDING_WITHDRAWN="FUNDING_REQUEST_WITHDRAWN",
  FUNDING_REJECTED="FUNDING_REJECTED",
  FUNDING_APPROVED="FUNDING_APPROVED",

  SHARE_LINK_CREATED="SHARE_LINK_CREATED",
  SHARE_LINK_ACCESSED="SHARE_LINK_ACCESSED",
  SHARE_LINK_DELETED="SHARE_LINK_DELETED",

}

