export enum DealProcessingStatus {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  AWAITING_AGREEMENT = 'AWAITING_AGREEMENT',
  FUNDING_REQUESTED = 'FUNDING_REQUESTED',
  FUNDS_RELEASED = 'FUNDS_RELEASED',
  LOAN_REPAID = 'LOAN_REPAID',
  WITHDRAWN = 'WITHDRAWN',
}

export enum ChecklistItemStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ADVERSE = 'ADVERSE',
  SATISFACTORY = 'SATISFACTORY',
}

export enum FundingDecisionType {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}