export enum TradeFinanceDealStatus {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS',
  FUNDING_REQUESTED = 'FUNDING_REQUESTED',
  REJECTED = 'REJECTED',
  AWAITING_AGREEMENT = 'AWAITING_AGREEMENT',
  AWAITING_FUNDS_RELEASE = 'AWAITING_FUNDS_RELEASE',
  FUNDS_RELEASED = 'FUNDS_RELEASED',
  LOAN_REPAID = 'LOAN_REPAID',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export enum TradeDetailFundingAction {
  FUNDING_REQUEST = 'FUNDING_REQUEST',
  WITHDRAW_REQUEST = 'WITHDRAW_REQUEST',
}