# Redis configuration for production
appendonly yes
appendfsync everysec

# security
protected-mode yes
requirepass FgWKNYvpwj1n6CITtQvqBRRwyxsQhIXg

# Persistence settings
save 900 1
save 300 10
save 60 10000

# Memory management
maxmemory 256mb
maxmemory-policy noeviction

# Connection
timeout 300
tcp-keepalive 60